require 'fileutils'

tsfile_list = Dir["./**/*.ts"]
build_dir = ENV["TSBUILD"]

# generate .js file by tsc
jsfile_list = tsfile_list.map do |tsfile|
  basename = tsfile.sub(/\.ts$/, ".js").sub(%r(^\./), "")
  "#{build_dir}/#{basename}"
end

jsfile_list.each{|jsfile|
  file jsfile => tsfile_list do |t|
    puts "Creating #{jsfile} from #{tsfile_list}..."
    `tsc --outDir #{build_dir}`
  end
  browserified_jsfile = jsfile.sub(/\.js$/, ".browserified.js")
  file browserified_jsfile => jsfile do |t|
    puts "Browserifying #{jsfile}..."
    `browserify #{jsfile} -o #{browserified_jsfile}`
  end
}


# default action
task default: jsfile_list
